[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.70.0",
    "requests>=2.32.3",
    "supabase>=2.15.0",
]
